FROM node:20-alpine AS builder

WORKDIR /app
COPY . .

# Build with env vars available
ARG NODE_ENV=production
ENV NODE_ENV=${NODE_ENV}

ARG TURSO_DATABASE_URL
ENV TURSO_DATABASE_URL=${TURSO_DATABASE_URL}

ARG TURSO_AUTH_TOKEN
ENV TURSO_AUTH_TOKEN=${TURSO_AUTH_TOKEN}

ARG YELP_API_KEY
ENV YELP_API_KEY=${YELP_API_KEY}

ARG NEXT_PUBLIC_GOOGLE_MAPS_API_KEY
ENV NEXT_PUBLIC_GOOGLE_MAPS_API_KEY=${NEXT_PUBLIC_GOOGLE_MAPS_API_KEY}

RUN npm install
RUN npm run build

FROM node:20-alpine AS runner

WORKDIR /app
ENV NODE_ENV production

COPY --from=builder /app ./

EXPOSE 3000
CMD ["npm", "start"]
