# fly.toml app configuration file generated for restaurant-matcher on 2025-06-27T19:53:09-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'restaurant-matcher'
primary_region = 'den'

[build]
  dockerfile = 'Dockerfile'

  [build.args]
    NEXT_PUBLIC_GOOGLE_MAPS_API_KEY = '${NEXT_PUBLIC_GOOGLE_MAPS_API_KEY}'
    TURSO_AUTH_TOKEN = '${TURSO_AUTH_TOKEN}'
    TURSO_DATABASE_URL = '${TURSO_DATABASE_URL}'
    YELP_API_KEY = '${YELP_API_KEY}'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
