name: Deploy to Fly.io

on:
  push:
    branches: [fly-io2]
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to Fly.io
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Fly.io CLI
        uses: superfly/flyctl-actions/setup-flyctl@master
        with:
          version: 'latest'

      - name: Deploy to Fly.io
        run: |
          # Set Fly.io API token
          flyctl auth token | tee /tmp/fly-api-token
          export FLY_API_TOKEN=$(cat /tmp/fly-api-token)
          
          # Deploy with build arguments
          flyctl deploy --remote-only \
            --build-arg TURSO_DATABASE_URL="$TURSO_DATABASE_URL" \
            --build-arg TURSO_AUTH_TOKEN="$TURSO_AUTH_TOKEN" \
            --build-arg YELP_API_KEY="$YELP_API_KEY" \
            --build-arg NEXT_PUBLIC_GOOGLE_MAPS_API_KEY="$NEXT_PUBLIC_GOOGLE_MAPS_API_KEY"
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
          TURSO_DATABASE_URL: ${{ secrets.TURSO_DATABASE_URL }}
          TURSO_AUTH_TOKEN: ${{ secrets.TURSO_AUTH_TOKEN }}
          YELP_API_KEY: ${{ secrets.YELP_API_KEY }}
          NEXT_PUBLIC_GOOGLE_MAPS_API_KEY: ${{ secrets.NEXT_PUBLIC_GOOGLE_MAPS_API_KEY }}
